[package]
name = "linguride-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
linguride-domain = { path = "../linguride-domain" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
