[package]
name = "mobile-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = "0.21"
linguride-core = { path = "../../crates/linguride-core" }
linguride-domain = { path = "../../crates/linguride-domain" }
serde.workspace = true
serde_json.workspace = true
